require("nvim-treesitter.configs").setup {
  ensure_installed = {
    "python",
    "comment",
    "lua",
    "json",
    "typescript",
    "cpp",
    "vue",
    "make",
    "css",
    "regex",
    "norg",
    "http",
    "c",
    "java",
    "jsonc",
    "hjson",
    "json5",
    "bash",
    "vim",
    "cmake",
    "yaml",
    "zig",
    "jsdoc",
    "tsx",
    "toml",
    "javascript",
    "kotlin",
    "ruby",
    "dockerfile",
    "html",
    "scss",
    "haskell",
  },
  sync_install = false,
  highlight = { enable = true },
  indent = { enable = true },
}

vim.opt.foldmethod = "expr"
vim.opt.foldexpr = "nvim_treesitter#foldexpr()"
